# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Dalton Manning
title: Process Controller & Automation Engineer
email: dalton
website: www.github.com/sproogen/resume-theme

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: facespics
github_username:  sproogen
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: jameswgrant
linkedin_username: Dalton-Manning
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: itsgoingto.be
  icon: fas fa-globe
  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Dalton and I'm a Level 1 Process Control & Automation Engineer. As well as experience in ETC, ETC ETC, ETC, GO ON ON HERE.

  I am most skilled in: <mark>ABB 800xA</mark>, <mark>Fanuc I30 6-Axis Robots</mark> and <mark>Allen Bradley Compact Logix</mark>

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Senior Project?
        link: github.com/sproogen
        # link_text: Project Website
        additional_links:
          - title:  sproogen/modern-resume-theme
            icon: fab fa-github
            url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          This was one of the most foundational projects I have lead in my life.
        description: | # this will include new lines to allow paragraphs
          Explain things here I ahve not gotten this far.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Nexteer Automotive
        link: nexteer.com
        # link_text: boringcompany.com
        sub_title: Mechanicall Engineer Co-op - Launch Team 
        caption: July 2022 - July 2024
        quote: >
          Learning fundamentals of manfacturing in Mechanical and Electrical components *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
           Explain things I did here I havent gotten this far yet.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Saginaw Valley State University
        caption: 2020 - 2024
        sub_title: Bachelor of Science in Mechanical Engineering
        quote: >
          say some random stuff about the school here.
        description: | # this will include new lines to allow paragraphs
          Talk about the things expereinced when i went here.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in mechanical and software engineering some of my other interests and hobbies are:
      - Exercise including running and weightlifting.
      - Cooking
      - Photography
      - [Think this just a md link he shows](https://www.youtube.com/watch?v=vtg4o__aRMg)

      Look at this cool image  
      ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
